<?php

/**
 * Caonical Host module for ProcessWire
 * 
 * Redirects all requests to hostname=$config->httpHosts[0] & optionally https
 *
 * ProcessWire 3.x
 * Copyright (C) 2016 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 *
 */

class CanonicalHost extends WireData implements Module, ConfigurableModule {
	public static function getModuleInfo() {
		return array(
			'title' => 'Canonical Host',
			'summary' => 'Redirects all requests to hostname=$config->httpHosts[0] (e.g., www.domain.tld rather than domain.tld) & optionally https',
			'version' => 001,
			'singular' => true,
			'autoload' => true,
		);
	}

	public function __construct() {
		if(!isset($this->data['https'])) $this->data['https'] = 0;
	}

	/** 
	 * Get constructed homepage URL
	 * @return string
	 */
	public static function baseUrl() {
		$https = modules()->getConfig(__CLASS__, 'https');
		$schema = $https ? 'https' : 'http';
		return $schema.'://'.config()->httpHosts[0];
	}

    /** 
     * Redirect if not canonical (1st specified) of httpHosts 
	 * or if HTTPS is set in config and not present URL scheme
     * 
     */
    public function init() {
        // if (php_sapi_name() == 'cli') return;
        $https = $this->data['https'] == 1 ? true : false;
		$url = $https ? 'httpsUrl' : 'httpUrl';
        $redirect = false;
        $relocate = wire('input')->$url([
          'withQueryString' => true, 
        //   'scheme' => $https ? 'https' : 'http'
        ]);/*
		// var_dump(wire('input')->scheme());
		// var_dump($this->data['https']);
		// var_dump($https);
		// echo $relocate;
		*/
        $hostname = wire('config')->httpHost;
        if ($https && !isset(($_SERVER['HTTPS']))) {
            $redirect = true;
        }
        $canonical = wire('config')->httpHosts[0];
        if ($hostname !== $canonical) {
            $redirect = true;
            $relocate = preg_replace("/({$hostname})/i", $canonical, $relocate, 1);
        }
        if ($redirect) wire('session')->redirect($relocate);
    }

	/**
	 * Module overview/configuration
     * - list httpHosts
     * - sitewide https?
	 */
	public static function getModuleConfigInputfields(array $data) {
		$inputfields = new InputfieldWrapper();

		// List httpHosts
		$listmarkup = '';
		foreach (wire('config')->httpHosts as $i) {
			$listmarkup .= '<li>'.$i.'</li>';
		}
		$listmarkup = '<ol>'.$listmarkup.'</ol>';
		$f = wire('modules')->get('InputfieldMarkup'); 
		$f->attr('name', 'hosts'); 
		$f->label = 'config httpHosts';
		$f->value = $listmarkup;
		$f->description = 'Present values';
		$f->notes = "Redirects to 1st";
		$inputfields->add($f);
    
		// Enforce HTTPS?
		$f = wire('modules')->get('InputfieldCheckbox'); 
		$f->attr('name', 'https');
		$f->label = 'Use HTTPS';
		if (@$data['https'] == 1) $f->attr('checked', $data['https']);
		$inputfields->add($f);

		return $inputfields;
	}
}
