<?php

/**
 * Caonical Host module for ProcessWire
 *
 * Options to redirect all requests to hostname=$config->httpHosts[0] & https, respectively
 *
 * ProcessWire 3.x
 * Copyright (C) 2016 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 *
 */

class CanonicalHost extends WireData implements Module, ConfigurableModule {
	public static function getModuleInfo() {
		return array(
			'title' => 'Canonical Host',
			'summary' => 'Options to redirect all requests to hostname=$config->httpHosts[0] (e.g., www.domain.tld rather than domain.tld) & https, respectively',
			'version' => 001,
			'singular' => true,
			'autoload' => true,
		);
	}

	public function __construct() {
		if(!isset($this->data['https'])) $this->data['https'] = 0;
		if(!isset($this->data['restrict_host'])) $this->data['restrict_host'] = 0;
	}

    /**
	 * Set sitewide https if enabled.
	 * Redirect to httpHosts[0] if enabled.
     *
     */
    public function init() {
		if ($this->data['https'] == 1)
		foreach (wire('templates') as $tpl) $tpl->https = 1;

		// if (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) return; // does in ddev
        // if (php_sapi_name() == 'cli') return;

		if ($this->data['restrict_host'] == 1 && wire('config')->httpHosts[0] !== wire('config')->httpHost) {
			$this->redirect();
		}
    }

    /**
     * Redirect if not 1st of httpHosts
     *
     */
	public function redirect() {
		$url = $this->data['https'] ? 'httpsUrl' : 'httpUrl';

        $relocate = wire('input')->$url([
          'withQueryString' => true,
        ]);

		$hostname = wire('config')->httpHost;
		$canonical = wire('config')->httpHosts[0];

		$relocate = preg_replace("/({$hostname})/i", $canonical, $relocate, 1);

		wire('session')->redirect($relocate);
	}

	/**
	 * Module overview/configuration
	 * - list httpHosts -- restrict to 1st?
     * - sitewide https?
	 */
	public static function getModuleConfigInputfields(array $data) {
		$inputfields = new InputfieldWrapper();

		// List httpHosts
		$listmarkup = '';
		foreach (wire('config')->httpHosts as $i) {
			$listmarkup .= '<li>'.$i.'</li>';
		}
		$listmarkup = '<ol>'.$listmarkup.'</ol>';
		$f = wire('modules')->get('InputfieldMarkup');
		$f->attr('name', 'hosts');
		$f->label = 'config httpHosts';
		$f->notes = 'Present values';
		$f->value = $listmarkup;
		$inputfields->add($f);

		// Restrict httpHost?
		$f = wire('modules')->get('InputfieldCheckbox');
		$f->attr('name', 'restrict_host');
		$f->label = 'Restrict to httpHosts[0]';
		$f->notes = "Redirects to 1st";
		if (@$data['restrict_host'] == 1) $f->attr('checked', $data['restrict_host']);
		$inputfields->add($f);

		// Enforce HTTPS?
		$f = wire('modules')->get('InputfieldCheckbox');
		$f->attr('name', 'https');
		$f->label = 'Use HTTPS';
		if (@$data['https'] == 1) $f->attr('checked', $data['https']);
		$inputfields->add($f);

		return $inputfields;
	}
}
